// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8f8WT5uaEB3J6BLOXeF9o27tBpsE9Dis',
    appId: '1:41965079417:web:88dc757cb4033e59d33da8',
    messagingSenderId: '41965079417',
    projectId: 'civicos-bb9f7',
    authDomain: 'civicos-bb9f7.firebaseapp.com',
    databaseURL: 'https://civicos-bb9f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'civicos-bb9f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwQ7yazlqXwP5PTvYyDXZhIK4skiwSiw',
    appId: '1:41965079417:android:122dc3fa548a5860d33da8',
    messagingSenderId: '41965079417',
    projectId: 'civicos-bb9f7',
    databaseURL: 'https://civicos-bb9f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'civicos-bb9f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbg_rGqvk9_YyeUtfrrLD8iiab5_ls65E',
    appId: '1:41965079417:ios:eccc0bcfae07f1ccd33da8',
    messagingSenderId: '41965079417',
    projectId: 'civicos-bb9f7',
    databaseURL: 'https://civicos-bb9f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'civicos-bb9f7.firebasestorage.app',
    iosBundleId: 'com.example.civicOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbg_rGqvk9_YyeUtfrrLD8iiab5_ls65E',
    appId: '1:41965079417:ios:eccc0bcfae07f1ccd33da8',
    messagingSenderId: '41965079417',
    projectId: 'civicos-bb9f7',
    databaseURL: 'https://civicos-bb9f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'civicos-bb9f7.firebasestorage.app',
    iosBundleId: 'com.example.civicOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8f8WT5uaEB3J6BLOXeF9o27tBpsE9Dis',
    appId: '1:41965079417:web:bc81447aaf2a7834d33da8',
    messagingSenderId: '41965079417',
    projectId: 'civicos-bb9f7',
    authDomain: 'civicos-bb9f7.firebaseapp.com',
    databaseURL: 'https://civicos-bb9f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'civicos-bb9f7.firebasestorage.app',
  );
}
